nit

diff --git a/youtube b/youtube
--- a/youtube
+++ b/youtube
@@ -6,62 +6,56 @@ vlc_opts="--play-and-exit"
 yt_opts=""
 link=""
 for arg in "$@"; do
-        case $arg in
-                --audio)
-                        yt_opts="--extract-audio --audio-quality 0"
-                        ;;
-                --loop)
-                        vlc_opts="${vlc_opts} --loop"
-                        ;;
-                --random)
-                        vlc_opts="${vlc_opts} --random"
-                        ;;
-                *)
-                        link=`echo $arg | grep "youtube.com\|youtu.be"`
-                        ;;
-        esac
-        shift
+  case $arg in
+    --audio)  yt_opts="--extract-audio --audio-quality 0" ;;
+    --loop)   vlc_opts="${vlc_opts} --loop" ;;
+    --random) vlc_opts="${vlc_opts} --random" ;;
+    *)        link=`echo $arg | grep "youtube.com\|youtu.be"` ;;
+  esac
+  shift
 done
 
 os=$(([[ -f /etc/lsb-release ]] && grep -q -i "Ubuntu" /etc/lsb-release) \
-        && echo "ubuntu" || echo "os x")
+  && echo "ubuntu" || echo "os x")
 if [[ "$os" == "os x" ]]; then
-        VLC="vlc"
-        [[ -z $link ]] && link=`pbpaste`
+  VLC="vlc"
+  [[ -z $link ]] && link=`pbpaste`
 else
-        [[ -z $link ]] && link=`xclip -selection clipboard -out`
+  [[ -z $link ]] && link=`xclip -selection clipboard -out`
 fi
 
 link=`echo "$link" | grep "youtube.com\|youtu.be"`
 if [ -z "$link" ]; then
-        echo "A youtube link was not found."
-        exit
+  echo "A youtube link was not found."
+  exit
 fi
 
 if [[ $link =~ list= ]]; then
-        yt_opts="${yt_opts} --ignore-errors"
+  yt_opts="${yt_opts} --ignore-errors"
 
-        directory=`youtube-dl --playlist-items 1 --get-filename --output "%(playlist_id)s" "$link"`
-        directory="/var/tmp/"$directory
-        if [ -d "${directory}" ] && [ "$(ls -A ${directory})" ]; then
-                $VLC $vlc_opts --quiet $directory/* &
-                exit
-        fi
+  directory=`youtube-dl --playlist-items 1 --get-filename \
+    --output "%(playlist_id)s" "$link"`
+  directory="/var/tmp/"$directory
+  if [ -d "${directory}" ] && [ "$(ls -A ${directory})" ]; then
+    $VLC $vlc_opts --quiet $directory/* &
+    exit
+  fi
 
-        mkdir -p $directory
-        youtube-dl $yt_opts --no-part --output "${directory}/%(id)s.%(ext)s" "$link" && \
-                $VLC $vlc_opts --quiet $directory/* &
+  mkdir -p $directory
+  youtube-dl $yt_opts --no-part --output "${directory}/%(id)s.%(ext)s" \
+    "$link" && \
+      $VLC $vlc_opts --quiet $directory/* &
 else
-        file=`youtube-dl $yt_opts --get-filename --output "%(id)s.%(ext)s" "$link"`
-        file="/var/tmp/"$file
-        if [ -e "${file%.*}."* ]; then
-                shopt -s extglob
-                file="${file%.*}."*
-                shopt -u extglob
-                $VLC $vlc_opts --quiet $file &
-                exit
-        fi
+  file=`youtube-dl $yt_opts --get-filename --output "%(id)s.%(ext)s" "$link"`
+  file="/var/tmp/"$file
+  if [ -e "${file%.*}."* ]; then
+    shopt -s extglob
+    file="${file%.*}."*
+    shopt -u extglob
+    $VLC $vlc_opts --quiet $file &
+    exit
+  fi
 
-        youtube-dl $yt_opts --no-part --output "$file" \
-                --exec "$VLC $vlc_opts --quiet {} &" "$link"
+  youtube-dl $yt_opts --no-part --output "$file" \
+    --exec "$VLC $vlc_opts --quiet {} &" "$link"
 fi
